Project/heart_rate_monitor/heart_rate_monitor/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace="main")),
)

Project/heart_rate_monitor/main/urls.py
from django.conf.urls import patterns, url

from main import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<sample_id>\d+)/current.png$', views.current_sample, name='current_sample'),
    url(r'^(?P<download_id>\d+)/download$', views.download, name='download')
)

Project/heart_rate_monitor/main/models.py
from django.db import models
from django.utils import timezone
import datetime

class Sample(models.Model):
	id = models.IntegerField(unique=True,primary_key=True)
	bpm_avg = models.FloatField(verbose_name="Average Beats per Minute",
		blank=True,null=True)
	sdann = models.FloatField(verbose_name="Heart Rate Variabilty (SDANN)",
		blank=True,null=True)
	duration = models.FloatField(verbose_name="Sample Duration",
		blank=True,null=True)
	time_rec = models.DateTimeField(verbose_name="Time Recorded",
		auto_now_add=True,blank=True,null=True) 	#sets time automatically on creation

	def get_menustring(self):		# for use in menus
		return 'Sample {0}: {1}'.format(self.id, 
			(timezone.localtime(self.time_rec)).strftime('%Y-%m-%d %H:%M'))

	def __unicode__(self):
		return str(self.id)

class Voltage(models.Model):
	dataset = models.ForeignKey(Sample)
	value = models.FloatField()
	time = models.FloatField()

	def __unicode__(self):
		return str((self.time,self.value))

class BPM(models.Model):
	dataset = models.ForeignKey(Sample)
	value = models.FloatField()
	time = models.FloatField()

	def __unicode__(self):
		return str((self.time,self.value))

Project/heart_rate_monitor/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt

from main.models import Sample, Voltage

def index(request):
	if 'sample_dropdown' in request.POST:
		key = request.POST['sample_dropdown']
	else:
		key = Sample.objects.last().id
	list_ = Sample.objects.all()
	current_ = Sample.objects.get(pk=key)

	return render(request, 'main/main.html', {'sample_list': list_, 'sample_id': key, 'sample': current_})
	# return HttpResponse(A)

def current_sample(request, sample_id = 0):
	fig=Figure(facecolor = "white")

	if sample_id:
		Data = Sample.objects.get(pk=sample_id)
	else:
		Data = Sample.objects.last()

	if Data.bpm_set.all():
		ax1 = fig.add_subplot(211)
		ax2 = fig.add_subplot(212)
	else:
		ax1 = fig.add_subplot(111)
		ax1.set_xlabel("Time (seconds)")

	xmax = Data.voltage_set.values_list().last()[3]
	ax1.axis([0,xmax,0,256])
	ax1.set_axis_bgcolor('white')
	ax1.set_title("Heart Rate Measurements -- Sample %i" % int(sample_id))
	ax1.set_ylabel("Relative Sensor Voltage")
	xx=[]
	yy=[]
	line1, = ax1.plot([], [], lw=1)
	ii = 0
	for item in Data.voltage_set.all():
		ii += 1
		xx.append(item.time)
		yy.append(item.value)
	line1.set_data(xx,yy)

	if Data.bpm_set.all():
		xmax = Data.bpm_set.values_list().last()[3]
		ax2.axis([0,xmax,0,180])
		line2, = ax2.plot([], [], lw=1)
		xx=[]
		yy=[]
		ii = 0
		for item in Data.bpm_set.all():
			ii += 1
			xx.append(item.time)
			yy.append(item.value)
		line2.set_data(xx,yy)
		ax2.set_ylabel("Beats per Minute (bpm)")
		ax2.set_xlabel("Time (seconds)")

	canvas=FigureCanvas(fig)
	response=HttpResponse(content_type='image/png')
	canvas.print_png(response)
	return response

def download(request, download_id):
    # response = HttpResponse(content_type='text/csv')
    # response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'

    # writer = csv.writer(response)
    # writer.writerow(['First row', 'Foo', 'Bar', 'Baz'])
    # writer.writerow(['Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"])

    # return response

	p = get_object_or_404(Sample, pk=download_id)
	response = HttpResponse(content_type='text/plain')
	response['Content-Disposition'] = 'attachment; filename="Sample%i.txt"' % int(download_id)
	for item in p.voltage_set.all():
		str_temp = ""
		str_temp += str(item.time)
		str_temp += " "
		str_temp += str(item.value)
		str_temp += "\n"
		response.write(str_temp)
	return response

Project/heart_rate_monitor/main/templates/main/main.html
<html>
<head>
	<title>Heart Rate Analyzer</title>
	<style>
  		body {margin:0;padding:0;min-height:100%;}
  		p {text-align:center;}
  		h1   {color:Black; text-align:center}
  		h4   {color:Black; text-align:center}
  		#Wrapper {min-height: 100%; position: relative}
  		#Header {padding:0px;}
  		#Content {padding-bottom: 80px}
  		#Textbody {float:left; width:39%; text-align:center; padding-left: 10px;}
  		#Data {float:right; width:59%; text-align:center}
  		#Statsleft {float:left; width:30%; text-align:center}
  		#Statsright {float:right; width:70%; text-align:center}
  		/*#Images {float:up;}  */
  		#Form {float:none; text-align:center;}
  		#Footer {position:relative; width:95%; bottom:0; left:5; right:5, text-align:center; padding-top: 20px; clear:both;}	
  		li {margin:10px 0px 0px 10px;}	
	</style>
</head>

<body>
	<div id="Wrapper">
		<div id="Header">
			{% load staticfiles %}
			<img src="{% static "main/heartbeat_graphic.png" %}" alt="Header" width = 100%/>
			<h4>by Ben Ebersole and Evan Ogden</h6>

		</div>
		<div id="Content">
			<div id="Textbody">
				<p>Welcome!</p>
				<p>To use this wonderful tool and analyze your heartbeat, follow these steps!</p>
				<ol style="text-align:left">
					<li>Lightly press the smooth side of the heartrate sensor against your finger or earlobe</li>
					<li>When ready to begin taking your sample, press the breadboard button to begin taking data</li>
					<li>When finished, press the breadboard button once more</li>
					<li>Select your sample by timestamp in the drop down menu, and click "Display Selected Sample". Note that the timestamp is set at the end of the test</li>
				</ol>
				<p> Note that you may need to take an initial test sample to ensure a comfortable position that gives a consistent reading.</p>
			</div>
			<div id="Data">
				<div id="Images">
					<img src="/main/{{sample_id}}/current.png" width = 80% />
				</div>
				<div id="Statsleft">
					<p> <b> BPM: </b> {{sample.bpm_avg}}</p>
					<p> <b> Duration: </b> {{sample.duration}}</p>
				</div>
				<div id="Statsright">
					<p> <b> Heartrate Variability(SDANN): </b> {{sample.sdann}}</p>
					<p> <b> Timestamp: </b> {{sample.time_rec}}</p>
				</div>

				<div id="Form">
					<form name="Selector" action="{% url 'main:index' %}" method="post">
					{% csrf_token %}
					<select name="sample_dropdown">
						{% for item in sample_list %}
						<option value="{{item.id}}">{{item.get_menustring}}</option>
						{% endfor %}
					</select>
					<input type="submit" value="Display Selected Sample" />
					</form>
					<!--form name="Downloader" action"{% url 'main:download' sample_id%}" method="post">
						{% csrf_token %}
						<input type="submit" value="Download Current Data Set"/>
					</form-->
				</div>
			</div>
		</div>
		<div id="Footer">
			<footer style="">
				<p>DISCLAIMER: <i> This device and the associated software are not intended to be used in an official medical setting. The hardware, software, and data returned should not be used in health evaluations or decision making. By using this, you (the user) agree that we (Ben Ebersole and Evan Ogden) are not liable for any actions taken in response to using this setup.</i> </p>
			</footer>
		</div>
	</div>
</body>

</html>